#!/usr/bin/bash
set -eu

if [[ $(whoami) != upgrade ]]; then
    exec sudo -u upgrade "${BASH_SOURCE[0]}"
fi

sudo pacman -Scc --noconfirm
rm -rf /home/upgrade/.cache/paru/clone/

# may be useful - cleans the folder including hidden files without complaining: 
# https://unix.stackexchange.com/questions/77127/rm-rf-all-files-and-all-hidden-files-without-error
#sudo -u upgrade find /home/upgrade/.cache -name . -o -prune -exec rm -rf -- {} +
