#!/usr/bin/bash
set -euxo pipefail

parse_config() { path=$1; desired_setting=$2;
    ret=''
    while IFS="=" read -r name value || [ -n "$name" ]; do
        name="$(xargs<<<$name)"
        value="$(xargs<<<${value//\"/})"
        if [[ "${name//\"/}" == $desired_setting ]]; then
            ret="${value//\"/}"
        fi
    done < "$path"
    echo $ret
}

get_bool() { name=$1
    [[ $(parse_config /etc/upgrade.conf $name) == true ]]
}


sudo -u upgrade sudo pacman -Syu --noconfirm

if get_bool upgrade_aur; then
    sudo -u upgrade paru --removemake --answerclean None --answerdiff None --answeredit None -Syu --noconfirm
fi

if get_bool clean_cache_on_success; then
    clearpkgcache
fi
