#!/usr/bin/bash
set -euo pipefail

if [[ $(whoami) != upgrade ]]; then
    exec sudo -u upgrade "${BASH_SOURCE[0]}"
fi

parse_config() { local path=$1; local desired_setting=$2;
    ret=''
    while IFS="=" read -r name value || [ -n "$name" ]; do
        name="$(xargs<<<$name)"
        value="$(xargs<<<${value//\"/})"
        if [[ "${name//\"/}" == $desired_setting ]]; then
            ret="${value//\"/}"
        fi
    done < "$path"
    echo $ret
}

get_bool() { local name=$1
    [[ $(parse_config /etc/upgrade.conf $name) == true ]]
}

echo Upgrading the system with pacman.
sudo pacman -Syu --noconfirm

if get_bool upgrade_aur; then
    if command -v yay >/dev/null; then
        echo Upgrading AUR packages with yay.
        yay --removemake -Syu --noconfirm
    elif command -v paru >/dev/null; then
        echo Upgrading AUR packages with paru.
        paru --removemake -Syu --noconfirm
    else
        echo No AUR helper found, skipping AUR package upgrades.
    fi
fi

if get_bool upgrade_flatpak && command -v flatpak >/dev/null; then
    echo Upgrading flatpak packages.
    sudo flatpak update --noninteractive
fi

if get_bool clean_cache_on_success; then
    clearpkgcache
fi
