#!/usr/bin/bash
set -euo pipefail

if [[ $(whoami) != upgrade ]]; then
    exec sudo -u upgrade "${BASH_SOURCE[0]}"
fi

parse_config() { local path=$1; local desired_setting=$2;
    ret=''
    while IFS="=" read -r name value || [ -n "$name" ]; do
        name="$(xargs<<<$name)"
        value="$(xargs<<<${value//\"/})"
        if [[ "${name//\"/}" == $desired_setting ]]; then
            ret="${value//\"/}"
        fi
    done < "$path"
    echo $ret
}

get_bool() { local name=$1
    [[ $(parse_config /etc/upgrade.conf $name) == true ]]
}

if get_bool upgrade_aur; then
    paru --removemake -Syu --noconfirm
else
    sudo pacman -Syu --noconfirm
fi

if get_bool upgrade_flatpak; then
    flatpak update
fi

if get_bool clean_cache_on_success; then
    clearpkgcache
fi
